# use an official node.js runtime as a parent image
FROM node:22-alpine

# set the working directory in the container
WORKDIR /app

# copy package.json and the package-lock.json files to container
COPY package*.json .

# install dependencies
RUN npm install

# copy the rest of the application (project-3 to /app in this case)
COPY . .

# expose the port that the app runs on 
EXPOSE 8000

# define the command to run your application
CMD ['node', './dist/index.js']
